on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: /
          build_path: ./dist
